[server]
runOnSave = true
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[logger]
level = "debug"

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
showErrorDetails = true
toolbarMode = "developer"

[runner]
fastReruns = true 